
#ifndef CLOCKTREE_H
#define CLOCKTREE_H

// This is largely infomational. Code can use these defines as inputs, 
// but any changes to this file will need code changes elsewhere. 
// Generally, updates will need to be made to the CubeMX ioc, the code
// must be regenerated, and relevent portions of the code will need to 
// be cherry picked and synced. 

#define CLOCKTREE_CPU_FREQ      600000000ULL

#define CLOCKTREE_PLL1P_FREQ    600000000ULL
#define CLOCKTREE_PLL1Q_FREQ    300000000ULL

#define CLOCKTREE_PLL2P_FREQ    200000000ULL
#define CLOCKTREE_PLL2Q_FREQ    100000000ULL
#define CLOCKTREE_PLL2S_FREQ    200000000ULL
#define CLOCKTREE_PLL2T_FREQ    400000000ULL

#define CLOCKTREE_PLL3P_FREQ    200000000ULL
#define CLOCKTREE_PLL3Q_FREQ    100000000ULL
#define CLOCKTREE_PLL3R_FREQ    100000000ULL
#define CLOCKTREE_PLL3S_FREQ     50000000ULL

#define CLOCKTREE_AHB1_FREQ     300000000ULL

#define CLOCKTREE_APB1_FREQ     150000000ULL
#define CLOCKTREE_APB1_FREQ     150000000ULL
#define CLOCKTREE_APB2_FREQ     150000000ULL
#define CLOCKTREE_APB4_FREQ     150000000ULL

#define CLOCKTREE_USART1_FREQ   CLOCKTREE_PLL3Q_FREQ
#define CLOCKTREE_USART2_8_FREQ CLOCKTREE_PLL3Q_FREQ
#define CLOCKTREE_LPUART1_FREQ  CLOCKTREE_PLL3Q_FREQ

#define CLOCKTREE_UART1_FREQ    CLOCKTREE_USART1_FREQ
#define CLOCKTREE_UART2_FREQ    CLOCKTREE_USART2_8_FREQ
#define CLOCKTREE_UART3_FREQ    CLOCKTREE_USART2_8_FREQ
#define CLOCKTREE_UART4_FREQ    CLOCKTREE_USART2_8_FREQ
#define CLOCKTREE_UART5_FREQ    CLOCKTREE_USART2_8_FREQ
#define CLOCKTREE_UART7_FREQ    CLOCKTREE_USART2_8_FREQ
#define CLOCKTREE_UART8_FREQ    CLOCKTREE_USART2_8_FREQ
#define CLOCKTREE_UART6_FREQ    CLOCKTREE_LPUART1_FREQ

#define CLOCKTREE_APB1_TIM_FREQ CLOCKTREE_APB1_FREQ * 2
#define CLOCKTREE_APB2_TIM_FREQ CLOCKTREE_APB2_FREQ * 2

#define CLOCKTREE_TIM1_FREQ     CLOCKTREE_APB2_TIM_FREQ
#define CLOCKTREE_TIM2_FREQ     CLOCKTREE_APB1_TIM_FREQ
#define CLOCKTREE_TIM3_FREQ     CLOCKTREE_APB1_TIM_FREQ
#define CLOCKTREE_TIM4_FREQ     CLOCKTREE_APB1_TIM_FREQ
#define CLOCKTREE_TIM5_FREQ     CLOCKTREE_APB1_TIM_FREQ
#define CLOCKTREE_TIM6_FREQ     CLOCKTREE_APB1_TIM_FREQ
#define CLOCKTREE_TIM7_FREQ     CLOCKTREE_APB1_TIM_FREQ
#define CLOCKTREE_TIM9_FREQ     CLOCKTREE_APB2_TIM_FREQ
#define CLOCKTREE_TIM12_FREQ    CLOCKTREE_APB1_TIM_FREQ
#define CLOCKTREE_TIM13_FREQ    CLOCKTREE_APB1_TIM_FREQ
#define CLOCKTREE_TIM14_FREQ    CLOCKTREE_APB1_TIM_FREQ
#define CLOCKTREE_TIM15_FREQ    CLOCKTREE_APB2_TIM_FREQ
#define CLOCKTREE_TIM16_FREQ    CLOCKTREE_APB2_TIM_FREQ
#define CLOCKTREE_TIM17_FREQ    CLOCKTREE_APB2_TIM_FREQ

#define CLOCKTREE_ADC_FREQ      CLOCKTREE_PLL2P_FREQ
#endif
